language: php

php:
  - 7.2
  - 7.3

env:
  - WP_VERSION=latest WP_MULTISITE=0

branches:
  except:
    - /^dist-.*$/

before_script:
  - bash bin/install-wp-tests.sh wordpress_test travis ''  localhost $WP_VERSION
  - composer install

script:
  - ./vendor/bin/phpcs . --extensions=php --warning-severity=8 -s --runtime-set testVersion 7.0
  - ./vendor/bin/phpunit
  - if [ -n "$AWS_ACCESS_KEY" ]; then ./vendor/bin/wpsnapshots configure 10up --aws_key=$AWS_ACCESS_KEY --aws_secret=$AWS_SECRET_ACCESS_KEY --user_name=Travis --user_email=travis@10up.com; fi
  - if [ -n "$AWS_ACCESS_KEY" ]; then bash run-wpacceptance.sh; fi

sudo: required

services:
  - mysql
  - docker
