[files]
extend-exclude = [
    ".git/",
    "tests/test-plugin/text-to-speech-voices.json"
]
ignore-hidden = false

[default]
extend-ignore-re = [
    "\\bTung Du\\b",
]

[default.extend-words]
# Typos
"weather" = "whether"

[default.extend-identifiers]
# Typos
"Github" = "GitHub"
"Wordpress" = "WordPress"
"Woocommerce" = "WooCommerce"
"get_post_stati" = "get_post_stati"
"Automattic" = "Automattic"
