<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'ClassifaiVendor\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'ClassifaiVendor\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'ClassifaiVendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'ClassifaiVendor\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'ClassifaiVendor\\JmesPath\\' => array($vendorDir . '/mtdowling/jmespath.php/src'),
    'ClassifaiVendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'ClassifaiVendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'ClassifaiVendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'ClassifaiVendor\\Aws\\' => array($vendorDir . '/aws/aws-sdk-php/src'),
);
