<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'b986a1bf9d2dc9e4419a354b73d10b35' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    '3f0eefdfa56af2234dc27a2c3c182299' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    'eff05afb766fdf89f82dfef78ae80046' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    '77675c5799721248d763f5196ff46d43' => $vendorDir . '/symfony/polyfill-mbstring/bootstrap.php',
    'f05e85342343fb69eff3b13469b46794' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
    'fbcbd9b60da98ffaba78eb89c14cc850' => $vendorDir . '/mtdowling/jmespath.php/src/JmesPath.php',
    '25c20262ddc80826fd9439d49277b46f' => $vendorDir . '/aws/aws-sdk-php/src/functions.php',
);
