name: Build release zip

on:
  release:
    types: [published]

jobs:
  build_zip:
    name: New release
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create ZIP
      run: |
        git archive --prefix=classifai/ HEAD -o classifai.zip

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{github.workspace}}/classifai.zip
        asset_name: classifai.zip
        asset_content_type: application/zip
