name: Build release zip

on:
  workflow_dispatch:

jobs:
  build_zip:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc
    - name: npm install and build
      run: |
        npm install
        npm run build
        npm run makepot
        composer install --no-dev
        npm run archive
    - name: Upload the ZIP file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}
        path: release
        retention-days: 2
