name: Build release zip

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_zip:
    name: Build release zip
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        cache: 'npm'
        node-version-file: .nvmrc

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      id: cache-composer
      uses: actions/cache@v4
      env:
        cache-name: cache-composer
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

    - name: Install node dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: npm ci --no-optional

    - name: Install composer dependencies
      if: steps.cache-composer.outputs.cache-hit != 'true'
      run: composer install --no-dev -o

    - name: Build
      run: |
        npm run build
        npm run makepot
        npm run archive

    - name: Upload the ZIP file as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}
        path: release
        retention-days: 2
