name: Build release zip

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build_zip:
    name: Build release zip
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup node
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        cache: 'npm'
        node-version-file: .nvmrc

    - name: Install node dependencies
      run: npm ci --no-optional

    - name: Install Composer dependencies
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
      with:
        composer-options: '--no-dev -o'

    - name: Build
      run: |
        npm run build
        npm run makepot
        npm run archive

    - name: Upload the ZIP file as an artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ github.event.repository.name }}
        path: release
        retention-days: 2
