name: Build release zip

on:
  workflow_dispatch:
  workflow_call:

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  build_zip:
    name: Build release zip
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        cache: 'npm'
        node-version-file: .nvmrc

    - name: Install node dependencies
      run: npm ci --no-optional

    - name: Install Composer dependencies
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
      with:
        composer-options: '--no-dev -o'

    - name: Build
      run: |
        npm run build
        npm run makepot
        npm run archive

    - name: Upload the ZIP file as an artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ github.event.repository.name }}
        path: release
        retention-days: 2
