name: Build Developer Docs

on:
  push:
    branches:
    - trunk

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup proper PHP version
      uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
      with:
        php-version: 8.3

    - name: Setup node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .nvmrc

    - name: Install dependencies and build assets
      run: |
        npm install
        npm run build
        npm run makepot
        composer install --no-dev -o

    - name: Build docs
      run: |
        npm run build:docs

    - name: Deploy docs update
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4.1.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: './docs/build'
