name: E2E Tests

on:
  push:
    branches:
      - develop
      - trunk
  # pull_request:
  #   branches:
  #     - develop

jobs:
  cypress:
    name: ${{ matrix.core.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        core:
          - {name: 'WP latest', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#6.1'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install

    - name: Composer (optional)
      run: composer update -W
      continue-on-error: true

    - name: Build (optional)
      run: npm run build
      continue-on-error: true

    - name: Set the core version
      run: ./tests/bin/set-core-version.js ${{ matrix.core.version }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Test
      run: npm run cypress:run

    - name: Update summary
      run: |
        npx mochawesome-merge ./tests/cypress/reports/*.json -o tests/cypress/reports/mochawesome.json
        rm -rf ./tests/cypress/reports/mochawesome-*.json
        npx mochawesome-json-to-md -p ./tests/cypress/reports/mochawesome.json -o ./tests/cypress/reports/mochawesome.md
        npx mochawesome-report-generator tests/cypress/reports/mochawesome.json -o tests/cypress/reports/
        cat ./tests/cypress/reports/mochawesome.md >> $GITHUB_STEP_SUMMARY

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-artifact-classifai
        retention-days: 7
        path: |
          ${{ github.workspace }}/tests/cypress/screenshots/
          ${{ github.workspace }}/tests/cypress/videos/
          ${{ github.workspace }}/tests/cypress/logs/
          ${{ github.workspace }}/tests/cypress/reports/
