name: Linting

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup node v16 and npm cache
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm

    - name: Install Node dependencies
      run: npm ci --no-optional

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.js
          **/*.json

    - name: Run JS linting
      run: |
        if [[ "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ]]; then
          npx wp-scripts lint-js ${{ steps.changed-files.outputs.all_changed_files }}
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          npm run lint:js
        fi

  phpcs:
    name: phpcs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set standard 10up cache directories
      run: |
        composer config -g cache-dir "${{ env.COMPOSER_CACHE }}"

    - name: Prepare composer cache
      uses: actions/cache@v3
      with:
        path: ${{ env.COMPOSER_CACHE }}
        key: composer-${{ env.COMPOSER_VERSION }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          composer-${{ env.COMPOSER_VERSION }}-

    - name: Set PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: none
        tools: composer:v2

    - name: Install dependencies
      run: composer install

    - name: Get updated PHP files
      id: changed-files
      uses: tj-actions/changed-files@v35
      with:
        files: |
          **/*.php

    - name: PHPCS check
      run: |
        if [[ "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ]]; then
          ./vendor/bin/phpcs ${{ steps.changed-files.outputs.all_changed_files }} --runtime-set testVersion 7.4-
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          ./vendor/bin/phpcs . --runtime-set testVersion 7.4-
        fi

  vipcs:
    name: vipcs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: VIPCS check
      uses: 10up/wpcs-action@stable
      with:
        enable_warnings: true
        standard: 'WordPress-VIP-Go'
        excludes: 'tests'
