name: Linting

env:
  COMPOSER_VERSION: "2"
  COMPOSER_CACHE: "${{ github.workspace }}/.composer-cache"

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Install node dependencies
      run: npm ci --no-optional

    - name: Get updated JS files
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        files: |
          **/*.js
          **/*.json

    - name: Run JS linting
      run: |
        if [[ "${{ steps.changed-files.outputs.any_changed }}" == 'true' && "${{ github.event_name }}" == "pull_request" ]]; then
          npx wp-scripts lint-js ${{ steps.changed-files.outputs.all_changed_files }}
        elif [[ "${{ github.event_name }}" == "push" ]]; then
          npm run lint:js
        fi
