name: PHP Linting

on:
  push:
    branches:
      - develop
      - trunk
    paths:
      - "**.php"
  pull_request:
    branches:
      - develop
    paths:
      - "**.php"

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup proper PHP version
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # v2.37.1
        with:
          php-version: 7.4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
        with:
          files: |
            **/*.php

      - name: Install Composer dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
        with:
          composer-options: '--prefer-dist'

      - name: Run PHP_CodeSniffer
        run: |
          HEAD_REF=$(git rev-parse HEAD)
          git checkout $HEAD_REF
          ./vendor/bin/phpcs-changed -s --git --git-base origin/${{ github.base_ref }} ${{ steps.changed-files.outputs.all_changed_files }}
