name: PHPStan

on:
  push:
    branches:
      - develop
      - trunk
    paths:
      - "**.php"
  pull_request:
    branches:
      - develop
    paths:
      - "**.php"

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        id: cache-composer
        uses: actions/cache@v4
        env:
          cache-name: cache-composer
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        run: composer install

      - name: PHPStan
        run: composer phpstan
