name: WordPress Plugin Checks

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: composer:v2

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install dependencies and build
        run: |
          npm ci --no-optional
          npm run build
          composer install

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          exclude-directories: 'node_modules,vendor'
