name: WordPress Plugin Checks

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  build:
    uses: 10up/classifai/.github/workflows/build-release-zip.yml@develop
    permissions:
      contents: read

  test:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Download built zip
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.event.repository.name }}

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{ github.event.repository.name }}

      - name: Run plugin check
        uses: wordpress/plugin-check-action@98a1788320d0add90df2d8183934ecccbc4e05d2 # v1.1.7
        with:
          build-dir: ${{ github.event.repository.name }}
          exclude-checks: 'plugin_readme,plugin_updater' # Plugin isn't on .org so excluding these for now.
          exclude-directories: 'assets,dist,vendor,vendor-prefixed'
          ignore-codes: 'PluginCheck.CodeAnalysis.DiscouragedFunctions.load_plugin_textdomainFound' # Plugin isn't on .org so we load the textdomain manually.
          ignore-warnings: true
