name: TEST Build Release
on:
  pull_request:
    branches:
      - develop

jobs:
  release:
    name: Push (merge) to trunk
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: npm install and build
      run: |
        npm install
        npm run build
        npm run makepot
        composer install --no-dev
        npm run archive
    - name: Release to Stable
      uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: test-305
          FOLDER: release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Release: ({sha}) {msg}'
