name: Spell Checker

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  Spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Spell Check
        uses: crate-ci/typos@aca895bf05aec0cb7dffa6f94495e923224d9f17 # v1.46.2
        with:
          files: ./
