name: Release to Stable

on:
  push:
    branches:
    - trunk

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  release:
    name: Push (merge) to trunk
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup node
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version-file: .nvmrc

    - name: Install dependencies and build assets
      run: |
        npm install
        npm run build
        npm run makepot

    - name: Install Composer dependencies
      uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0
      with:
        composer-options: '--no-dev -o'

    - name: Build release asset
      run: |
        npm run archive

    - name: Release to Stable
      uses: s0/git-publish-subdir-action@ac113f6bfe8896e85a373534242c949a7ea74c98 # develop
      env:
        REPO: self
        BRANCH: stable
        FOLDER: release
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: 'Release: ({sha}) {msg}'
