name: VIPCS

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**/*.php'
      - 'phpcs.xml*'
  push:
    branches:
      - develop
      - trunk
    paths:
      - '**/*.php'
      - 'phpcs.xml*'

jobs:
  vipcs:
    name: VIPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run VIPCS
        uses: 10up/wpcs-action@4b2d47a70e3a0a9c08b40a4a90bc3ccbbdc12b3f # v1.7.0
        with:
          standard: WordPress-VIP-Go
          use_local_config: false
          enable_warnings: false
          only_changed_lines: false
          excludes: tests
