name: VIPCS

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - '**/*.php'
      - 'phpcs.xml*'
  push:
    branches:
      - develop
      - trunk
    paths:
      - '**/*.php'
      - 'phpcs.xml*'

jobs:
  vipcs:
    name: VIPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run VIPCS
        uses: 10up/wpcs-action@39f1a9eb6139795e6798d11b51eeecf5a9678ccc # v2.1.0
        with:
          standard: WordPress-VIP-Go
          use_local_config: false
          enable_warnings: false
          only_changed_lines: false
          excludes: tests
