name: WordPress version checker

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop
  schedule:
    - cron: '0 0 * * 1'

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  wordpress-version-checker:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: WordPress version checker
        uses: skaut/wordpress-version-checker@9d247334f5b30202cb9c1f4aee74c52f37399f69 # v2.2.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
